// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/organiser-dashboard/Aurora.tsx": () => import("../components/mockups/organiser-dashboard/Aurora.tsx"),
  "./components/mockups/organiser-dashboard/Obsidian.tsx": () => import("../components/mockups/organiser-dashboard/Obsidian.tsx"),
  "./components/mockups/organiser-dashboard/Vivid.tsx": () => import("../components/mockups/organiser-dashboard/Vivid.tsx")
};
